### PR TITLE
Preliminary results from NotreDame-FRED team. Abstract not yet ready. 

### PR DESCRIPTION
**Pull request by confunguido**
Still working on the abstract. Will submit when ready.

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @confunguido ,

Thank you very much for your submissions.

The automatic validation is still in progress I apologize for the inconvenience. In the meantime, I will do the validation manually. Please find below this message the result of the validation.

To add some information on the validation:
- the error 102 (incorrect number of column) refers to the missing `age_group` column: "The age_group are optionals, however, the submission should contain at least one age group: `0-130`, if multiples age_group are provided the overall population should still be provided with the age group `0-130`."
- the error 501 (missing point values) appears because the 'peak time hosp' target requires only point value. If the target is not included in the submission feel free to ignore this error.

I also have a question about the abstract. I noticed that for some sections, the information is not filled. I can keep the PR open until the abstract is totally filled or if you prefer you can remove it from this PR and open another PR when the abstract is filled. I can merge the PR once the abstract is filled or removed.

Please feel free to let me know if you have any questions or if I can be of any help.
Thanks,

Lucie

"Run validation on file: 2022-08-14-NotreDame-FRED.csv"

 ## Columns: 

 ❌ Error 102: The data frame should contains 10 columns, not 9. Please verify if one or multiple columns have been added or are missing. 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 ❌ Error 501: The data frame is missing point value. 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'peak time hosp' target(s).
🟡 Warning 602: The data frame does not contain projections for 'peak size hosp' target(s).
❌ Error 603: The target_end_date should correspond to the end of the epiweek (Saturday). For example, if the 1st week projection is on the week starting 2021-11-14 and ending 2021-11-20. The target_end_week for this week should be: 2021-11-20.
🟡 Warning 605: The projections should contains at least 42 weeks of projection. The data frame contains only: 35 week(s). The projection might not be included in the Ensembles.
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : A-2022-08-14, location : 18, target_name : cum death
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : B-2022-08-14, location : 18, target_name : cum death
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : C-2022-08-14, location : 18, target_name : cum death
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : D-2022-08-14, location : 18, target_name : cum death
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : A-2022-08-14, location : 18, target_name : cum hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : B-2022-08-14, location : 18, target_name : cum hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : C-2022-08-14, location : 18, target_name : cum hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : D-2022-08-14, location : 18, target_name : cum hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : A-2022-08-14, location : 18, target_name : inc death
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : B-2022-08-14, location : 18, target_name : inc death
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : C-2022-08-14, location : 18, target_name : inc death
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : D-2022-08-14, location : 18, target_name : inc death
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : A-2022-08-14, location : 18, target_name : inc hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : B-2022-08-14, location : 18, target_name : inc hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : C-2022-08-14, location : 18, target_name : inc hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : D-2022-08-14, location : 18, target_name : inc hosp
❌ Error 608: 1st week target end date is not valid. It should be: '2022-08-20' but it is: '2022-10-06'.
❌ Error 609: One or multiple target(s) end date are not valid. For 1 wk ahead, the target_end_date should be: 2022-08-20
❌ Error 609: One or multiple target(s) end date are not valid. For 10 wk ahead, the target_end_date should be: 2022-10-22
❌ Error 609: One or multiple target(s) end date are not valid. For 11 wk ahead, the target_end_date should be: 2022-10-29
❌ Error 609: One or multiple target(s) end date are not valid. For 12 wk ahead, the target_end_date should be: 2022-11-05
❌ Error 609: One or multiple target(s) end date are not valid. For 13 wk ahead, the target_end_date should be: 2022-11-12
❌ Error 609: One or multiple target(s) end date are not valid. For 14 wk ahead, the target_end_date should be: 2022-11-19
❌ Error 609: One or multiple target(s) end date are not valid. For 15 wk ahead, the target_end_date should be: 2022-11-26
❌ Error 609: One or multiple target(s) end date are not valid. For 16 wk ahead, the target_end_date should be: 2022-12-03
❌ Error 609: One or multiple target(s) end date are not valid. For 17 wk ahead, the target_end_date should be: 2022-12-10
❌ Error 609: One or multiple target(s) end date are not valid. For 18 wk ahead, the target_end_date should be: 2022-12-17
❌ Error 609: One or multiple target(s) end date are not valid. For 19 wk ahead, the target_end_date should be: 2022-12-24
❌ Error 609: One or multiple target(s) end date are not valid. For 2 wk ahead, the target_end_date should be: 2022-08-27
❌ Error 609: One or multiple target(s) end date are not valid. For 20 wk ahead, the target_end_date should be: 2022-12-31
❌ Error 609: One or multiple target(s) end date are not valid. For 21 wk ahead, the target_end_date should be: 2023-01-07
❌ Error 609: One or multiple target(s) end date are not valid. For 22 wk ahead, the target_end_date should be: 2023-01-14
❌ Error 609: One or multiple target(s) end date are not valid. For 23 wk ahead, the target_end_date should be: 2023-01-21
❌ Error 609: One or multiple target(s) end date are not valid. For 24 wk ahead, the target_end_date should be: 2023-01-28
❌ Error 609: One or multiple target(s) end date are not valid. For 25 wk ahead, the target_end_date should be: 2023-02-04
❌ Error 609: One or multiple target(s) end date are not valid. For 26 wk ahead, the target_end_date should be: 2023-02-11
❌ Error 609: One or multiple target(s) end date are not valid. For 27 wk ahead, the target_end_date should be: 2023-02-18
❌ Error 609: One or multiple target(s) end date are not valid. For 28 wk ahead, the target_end_date should be: 2023-02-25
❌ Error 609: One or multiple target(s) end date are not valid. For 29 wk ahead, the target_end_date should be: 2023-03-04
❌ Error 609: One or multiple target(s) end date are not valid. For 3 wk ahead, the target_end_date should be: 2022-09-03
❌ Error 609: One or multiple target(s) end date are not valid. For 30 wk ahead, the target_end_date should be: 2023-03-11
❌ Error 609: One or multiple target(s) end date are not valid. For 31 wk ahead, the target_end_date should be: 2023-03-18
❌ Error 609: One or multiple target(s) end date are not valid. For 32 wk ahead, the target_end_date should be: 2023-03-25
❌ Error 609: One or multiple target(s) end date are not valid. For 33 wk ahead, the target_end_date should be: 2023-04-01
❌ Error 609: One or multiple target(s) end date are not valid. For 34 wk ahead, the target_end_date should be: 2023-04-08
❌ Error 609: One or multiple target(s) end date are not valid. For 35 wk ahead, the target_end_date should be: 2023-04-15
❌ Error 609: One or multiple target(s) end date are not valid. For 4 wk ahead, the target_end_date should be: 2022-09-10
❌ Error 609: One or multiple target(s) end date are not valid. For 5 wk ahead, the target_end_date should be: 2022-09-17
❌ Error 609: One or multiple target(s) end date are not valid. For 6 wk ahead, the target_end_date should be: 2022-09-24
❌ Error 609: One or multiple target(s) end date are not valid. For 7 wk ahead, the target_end_date should be: 2022-10-01
❌ Error 609: One or multiple target(s) end date are not valid. For 8 wk ahead, the target_end_date should be: 2022-10-08
❌ Error 609: One or multiple target(s) end date are not valid. For 9 wk ahead, the target_end_date should be: 2022-10-15 

## Locations: 

 ❌ Error 703: The target inc death should only contain the location(s):US, the data frame contains other locations (18), please verify.
❌ Error 703: The target cum death should only contain the location(s):US, the data frame contains other locations (18), please verify. 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by confunguido** [comment]
Hi @LucieContamin,

Thank you for your comments. I will work on making those corrections. About the abstract, I just made an outline for now. Would it be okay to submit that later after the projections? I'm more concerned about getting the projections right. 

Thanks,
Guido

**Comment by LucieContamin** [comment]
Hi Guido,

For your question about the abstract, please feel free to remove it from this Pull-Request and resubmit it later in another PR. 
Please feel free to let me know if you have any questions,

Best, Lucie

**Comment by LucieContamin** [comment]
Sorry for the double message, could I also ask to rename the metadata file to fit the standard name (`metadata-NotreDame-FRED.txt`), please? 
The metadata file name should have the following format

`metadata-team-model.txt`

where

-    `team` is the teamname and
 -   `model` is the name of your model.

Many thanks, Lucie

**Comment by confunguido** [comment]
Hi @LucieContamin, 

I addressed your comments. Hope this version is better.

**Comment by LucieContamin** [comment]
Hi @confunguido ,

Thank you for the update. Please find below the results of the validation.

To add some information on the validation:

 -  the error 501 (missing point values) appears because the 'peak time hosp' target requires only point value. If this target is not included in the submission feel free to ignore this error.
- the error 703 (unexpected location) appears because the death targets are only required for national level.

Please feel free to let me know if you have any questions or need more information on the validation output,

Best, Lucie

[1] "Run validation on file: 2022-08-14-NotreDame-FRED.csv"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 ❌ Error 501: The data frame is missing point value. 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'peak time hosp' target(s).
🟡 Warning 602: The data frame does not contain projections for 'peak size hosp' target(s).
❌ Error 603: The target_end_date should correspond to the end of the epiweek (Saturday). For example, if the 1st week projection is on the week starting 2021-11-14 and ending 2021-11-20. The target_end_week for this week should be: 2021-11-20.
❌ Error 608: 1st week target end date is not valid. It should be: '2022-08-20' but it is: '2022-08-16'.
❌ Error 609: One or multiple target(s) end date are not valid. For 1 wk ahead, the target_end_date should be: 2022-08-20
❌ Error 609: One or multiple target(s) end date are not valid. For 10 wk ahead, the target_end_date should be: 2022-10-22
❌ Error 609: One or multiple target(s) end date are not valid. For 11 wk ahead, the target_end_date should be: 2022-10-29
❌ Error 609: One or multiple target(s) end date are not valid. For 12 wk ahead, the target_end_date should be: 2022-11-05
❌ Error 609: One or multiple target(s) end date are not valid. For 13 wk ahead, the target_end_date should be: 2022-11-12
❌ Error 609: One or multiple target(s) end date are not valid. For 14 wk ahead, the target_end_date should be: 2022-11-19
❌ Error 609: One or multiple target(s) end date are not valid. For 15 wk ahead, the target_end_date should be: 2022-11-26
❌ Error 609: One or multiple target(s) end date are not valid. For 16 wk ahead, the target_end_date should be: 2022-12-03
❌ Error 609: One or multiple target(s) end date are not valid. For 17 wk ahead, the target_end_date should be: 2022-12-10
❌ Error 609: One or multiple target(s) end date are not valid. For 18 wk ahead, the target_end_date should be: 2022-12-17
❌ Error 609: One or multiple target(s) end date are not valid. For 19 wk ahead, the target_end_date should be: 2022-12-24
❌ Error 609: One or multiple target(s) end date are not valid. For 2 wk ahead, the target_end_date should be: 2022-08-27
❌ Error 609: One or multiple target(s) end date are not valid. For 20 wk ahead, the target_end_date should be: 2022-12-31
❌ Error 609: One or multiple target(s) end date are not valid. For 21 wk ahead, the target_end_date should be: 2023-01-07
❌ Error 609: One or multiple target(s) end date are not valid. For 22 wk ahead, the target_end_date should be: 2023-01-14
❌ Error 609: One or multiple target(s) end date are not valid. For 23 wk ahead, the target_end_date should be: 2023-01-21
❌ Error 609: One or multiple target(s) end date are not valid. For 24 wk ahead, the target_end_date should be: 2023-01-28
❌ Error 609: One or multiple target(s) end date are not valid. For 25 wk ahead, the target_end_date should be: 2023-02-04
❌ Error 609: One or multiple target(s) end date are not valid. For 26 wk ahead, the target_end_date should be: 2023-02-11
❌ Error 609: One or multiple target(s) end date are not valid. For 27 wk ahead, the target_end_date should be: 2023-02-18
❌ Error 609: One or multiple target(s) end date are not valid. For 28 wk ahead, the target_end_date should be: 2023-02-25
❌ Error 609: One or multiple target(s) end date are not valid. For 29 wk ahead, the target_end_date should be: 2023-03-04
❌ Error 609: One or multiple target(s) end date are not valid. For 3 wk ahead, the target_end_date should be: 2022-09-03
❌ Error 609: One or multiple target(s) end date are not valid. For 30 wk ahead, the target_end_date should be: 2023-03-11
❌ Error 609: One or multiple target(s) end date are not valid. For 31 wk ahead, the target_end_date should be: 2023-03-18
❌ Error 609: One or multiple target(s) end date are not valid. For 32 wk ahead, the target_end_date should be: 2023-03-25
❌ Error 609: One or multiple target(s) end date are not valid. For 33 wk ahead, the target_end_date should be: 2023-04-01
❌ Error 609: One or multiple target(s) end date are not valid. For 34 wk ahead, the target_end_date should be: 2023-04-08
❌ Error 609: One or multiple target(s) end date are not valid. For 35 wk ahead, the target_end_date should be: 2023-04-15
❌ Error 609: One or multiple target(s) end date are not valid. For 36 wk ahead, the target_end_date should be: 2023-04-22
❌ Error 609: One or multiple target(s) end date are not valid. For 37 wk ahead, the target_end_date should be: 2023-04-29
❌ Error 609: One or multiple target(s) end date are not valid. For 38 wk ahead, the target_end_date should be: 2023-05-06
❌ Error 609: One or multiple target(s) end date are not valid. For 39 wk ahead, the target_end_date should be: 2023-05-13
❌ Error 609: One or multiple target(s) end date are not valid. For 4 wk ahead, the target_end_date should be: 2022-09-10
❌ Error 609: One or multiple target(s) end date are not valid. For 40 wk ahead, the target_end_date should be: 2023-05-20
❌ Error 609: One or multiple target(s) end date are not valid. For 41 wk ahead, the target_end_date should be: 2023-05-27
❌ Error 609: One or multiple target(s) end date are not valid. For 42 wk ahead, the target_end_date should be: 2023-06-03
❌ Error 609: One or multiple target(s) end date are not valid. For 5 wk ahead, the target_end_date should be: 2022-09-17
❌ Error 609: One or multiple target(s) end date are not valid. For 6 wk ahead, the target_end_date should be: 2022-09-24
❌ Error 609: One or multiple target(s) end date are not valid. For 7 wk ahead, the target_end_date should be: 2022-10-01
❌ Error 609: One or multiple target(s) end date are not valid. For 8 wk ahead, the target_end_date should be: 2022-10-08
❌ Error 609: One or multiple target(s) end date are not valid. For 9 wk ahead, the target_end_date should be: 2022-10-15 

## Locations: 

 ❌ Error 703: The target inc death should only contain the location(s):US, the data frame contains other locations (18), please verify.
❌ Error 703: The target cum death should only contain the location(s):US, the data frame contains other locations (18), please verify. 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by confunguido** [comment]
I removed the deaths, and I think the dates should be fixed too.

**Comment by LucieContamin** [comment]
Hi @confunguido ,

Thank you very much for the update. Please find below the last version of the validation.
If the warnings 602 are expected, I will ignore the error 501 and merge the PR.

Please let me know if any other questions,

Best, Lucie

[1] "Run validation on file: 2022-08-14-NotreDame-FRED.csv"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 ❌ Error 501: The data frame is missing point value. 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'inc death' target(s).
🟡 Warning 602: The data frame does not contain projections for 'cum death' target(s).
🟡 Warning 602: The data frame does not contain projections for 'peak time hosp' target(s).
🟡 Warning 602: The data frame does not contain projections for 'peak size hosp' target(s). 

## Locations: 

 No errors or warnings found on Location 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by LucieContamin** [comment]
Hi @confunguido ,

Sorry for the multiple messages. I also have a question about the metadata file. Your metadata file contains the field" `team_model_designation: primary`. This field is not required/optional in the metadata file, would it be possible to remove it and/or move the information to another field, please?

Many thanks,

Lucie

**Comment by confunguido** [comment]
Hi @LucieContamin,

Sorry about that. I basically just copied the metadata from our covid model. I just removed that filed.

**Comment by LucieContamin** [comment]
Hi again,

Thank you very much for the update. 
Best, Lucie

**Pull request merged**
