### PR TITLE
Round 3 projections - UVA FluXSim

### PR DESCRIPTION
**Pull request by srinivvenkat**
No changes to calibration. Updated using data until December 3rd (as observed on December 12th).

### CODE REVIEW

**Comment by srinivvenkat** [comment]
@LucieContamin Just confirming if this validation error is the expected behavior. We were using the first day of projections as model projection day until Round 2 (even though our models were getting run a bit later than that). Then I noticed this language in README that said:

> Model projections will have an associated model_projection_date that corresponds to the day the projection was made.

So, I modified that to say 2022-12-12 for the Round 3 submission. This is also to account for the fact that there is backfill in the ground truth (we used the data until 2022-12-04 as observed on 2022-12-12). We believe that it is appropriate to capture this somewhere in the submission, although it conflicts with the interpretation of "1-week ahead", etc. 

Please let us know if we should modify this back to 2022-12-04 or let it stay as is. 

P.S.: There's also a warning w.r.t number of projection weeks. Noticed that we submitted 29 weeks out instead of 26 weeks. Can update that once you confirm about model_projection_date.

**Comment by LucieContamin** [comment]
Hi @srinivvenkat ,

I apologize the confusion, I updated the READMEs to clarify the information for this column:
```
Model projections will have an associated model_projection_date that correspond to the start date for scenarios (first date of simulated transmission/outcomes). The "model_projection_date" and date in the filename should correspond.
```
So in this case, for FLU round 3, the date in the filename and the data in the model_projection_date column should be the same and should be "2022-12-04".

You can store additional information in the abstract, if necessary.

The warning about the additional week does not stop the merging of the submission, just the additional 3 weeks will not be included in the Ensembles and Visualization. 

Please let me know if any questions or issues,
Best,

Lucie

**Comment by srinivvenkat** [comment]
Thanks Lucie for the clarification. Have updated the submission with 2022-12-04 as the model_projection_date and truncated forecast horizon to 26 weeks. "Model Run Date" is now recorded in the Model Calibration section of the abstract.

Moving forward, we think it'd be good to record the Model Run Date for each round in the metadata explicitly (if not as an additional column to the Hub format). In addition to the impact of backfill on the calibration data, this also controls for the "out-of-sample" data available to the modelers. We have usually seen 1-2 weeks spread across the model submissions, which could lead to different amount of information available. Hope that makes sense. 

If time permits, would be useful to discuss this with coordination team and other modelers this week.

Thanks for the prompt response as always!

Regards,
Srini

**Comment by LucieContamin** [comment]
Thank you very much for quick update and for the idea. 
I will transmit your idea, I agree it would be useful to talk about it. 

Best, Lucie

**Pull request merged**
