### PR TITLE
UVA-EpiHiperFlu Round 1 submission

### PR DESCRIPTION
**Pull request by chenj-uva**
Projections (including sample data) from UVA-EpiHiper team with a different hospitalization calibration. Should be weighted equally as our previous submission (model "UVA-EpiHiper").

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @chenj-uva ,

Thank you very much for your submissions and the additional information, we will weight this projection equally to the other UVA-EpiHiper submission (0.5 each).

The automatic validation is still in progress I apologize for the inconvenience. In the meantime, I will do the validation manually. Please find below this message the result of the validation for the 2 submissions files. Is the warning expected?

For the abstract, the template changes slightly to include a model calibration part (https://github.com/midas-network/flu-scenario-modeling-hub/blob/main/data-processed/MyTeam-MyModel/2022-08-14-MyTeam-MyModel-abstract.md) would it be possible to add it, please?

Please feel free to let me know if you have any questions or if I can be of any help.
Thanks,

[1] "Run validation on file: 2022-08-14-UVA-EpiHiperFlu.csv.gz"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 No errors or warnings found on Value and Type columns 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'inc death' target(s).
🟡 Warning 602: The data frame does not contain projections for 'cum death' target(s). 

## Locations: 

 No errors or warnings found on Location 

## Age Group: 

 No errors or warnings found on Age_group 
 
-------
 
 [1] "Run validation on file: 2022-08-14-UVA-EpiHiperFlu-sample.csv.gz"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No 'quantile' information required, no validation runs for Quantiles information 

## Sample: 

 No errors or warnings found on Sample 

## Value and Type Columns: 

 🟡 Warning 505: Multiples location/target/scenario groups have a unique value for the whole projection period. Please verify. 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'inc death' target(s). 

## Locations: 

 No errors or warnings found on Location 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by chenj-uva** [comment]
Hi @LucieContamin 

The abstract had calibration information (under General Model Description) which I now have copied to the new "Model Calibration" section. Regarding the warnings, 602 (no death projections) is expected. I am not sure what warning 505 means. Any example (one example location/target/scenario group) so that I can check? Thank you!

Best,
Jiangzhuo Chen

**Comment by LucieContamin** [comment]
Hi @chenj-uva ,

Thanks for the abstract update and the additional information, 
For the warning 505, I join here 10 examples groups. The message got automatically shorten when multiple groups have the warnings to shorten the length of the output report, but I am happy to provide more detailed information if necessary.

Also just a reminder, the warnings are not blocking the submission. It's just to verify that is expected, if so I will merge the PR.

Many thanks,
Lucie

   [1] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : A-2022-08-14, location : 10, sample : 1, age_group : 0-130, target_name : inc hosp" 
   [2] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : A-2022-08-14, location : 31, sample : 1, age_group : 0-130, target_name : inc hosp" 
   [3] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : C-2022-08-14, location : 31, sample : 1, age_group : 0-130, target_name : inc hosp" 
   [4] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : D-2022-08-14, location : 33, sample : 1, age_group : 0-130, target_name : inc hosp" 
   [5] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : B-2022-08-14, location : 50, sample : 1, age_group : 0-130, target_name : inc hosp" 
   [6] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : C-2022-08-14, location : 56, sample : 1, age_group : 0-130, target_name : inc hosp" 
   [7] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : D-2022-08-14, location : 56, sample : 1, age_group : 0-130, target_name : inc hosp" 
   [8] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : B-2022-08-14, location : 15, sample : 2, age_group : 0-130, target_name : inc hosp" 
   [9] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : A-2022-08-14, location : 38, sample : 2, age_group : 0-130, target_name : inc hosp" 
  [10] "🟡 Warning 505: Some location/target/scenario groups have a unique value for the whole projection period. Please verify: scenario_id : C-2022-08-14, location : 46, sample : 2, age_group : 0-130, target_name : inc hosp"

**Comment by chenj-uva** [comment]
Hi @LucieContamin 

I have checked the data. These warnings seem to be fine. Please go ahead merge the PR. Thank you!

Best,
Jiangzhuo Chen

**Comment by chenj-uva** [comment]
@LucieContamin 

Forgot to say that the two "EpiHiper" submissions should be weighted equally, but not 0.5 each. I meant that we treat them as projections of two models, each weighted as a single model just like any other model. Please let me know your thoughts. Thank you!

Best,
Jiangzhuo Chen

**Comment by LucieContamin** [comment]
Hi @chenj-uva ,

Thanks for the information, I will merge the PR. 

Best, Lucie

**Pull request merged**
