### PR TITLE
NIH model

### PR DESCRIPTION
**Pull request by aperofsky**
Pull request for NIH Flu_TS model

### CODE REVIEW

**Comment by aperofsky** [comment]
I submitted an additional file with a "subscenario" column because I have subscenario projections for A-D. The main submission file does not have this column and provides only the aggregate projection

**Comment by LucieContamin** [comment]
Hi @aperofsky ,

Thank you very much for your submissions.

The automatic validation is still in progress I apologize for the inconvenience. In the meantime, I will do the validation manually. Please find below this message the result of the validation.

Just for information, on the validation, I only run it on the 2022-08-14-NIH-Flu_TS.csv file for now:
 -  the warnings are not blocking the submission. It's just to verify that is expected. For example, you can see the warning: "Warning 602: The data frame does not contain projections for 'inc death' target(s)." If it's expected I will ignore this warning.
 - Also just to verify, the submission seems to contain projection for the national level only, is that expected?

Please feel free to let me know if you have any questions or if I can be of any help.
Thanks,

Lucie

 "Run validation on file: 2022-08-14-NIH-Flu_TS.csv"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 No errors or warnings found on Value and Type columns 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'inc death' target(s).
🟡 Warning 602: The data frame does not contain projections for 'cum death' target(s). 

## Locations: 

 No errors or warnings found on Location 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by LucieContamin** [comment]
For the `2022-08-14-NIH-Flu_TS_subscenarios.csv` file, I would like to thank you for the additional information. However, we don't accept any new format for now. 
Would it be possible to remove it from the Pull-Request for now, please?

**Comment by aperofsky** [comment]
Hi @LucieContamin, I am providing projections for just hospitalizations and not deaths so that warning is to be expected. I am also only providing national projections, so that's also expected. I'll remove the extra file. Thanks!

**Comment by LucieContamin** [comment]
Hi again @aperofsky !

Thank you for the quick answer and the additional information. I will merge the PR once the extra file is removed.
Many thanks,

Lucie

**Pull request merged**
