### PR TITLE
Submission of CADPH flu scenarios for CA for round 1

### PR DESCRIPTION
**Pull request by whit1951**
Includes:
- 2022-08-14-CADPH-FluCAT-abstract.md
- 2022-08-14-CADPH-FluCAT.csv (results for state of CA only)
- metadata-CADPH-FluCAT.txt

tagging @tomasleon  for awareness

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @whit1951,

Thank you very much for your submissions. 

The automatic validation is still in progress I apologize for the inconvenience. In the meantime, I will do the validation manually. Please find below this message the result of the validation.

Just for information, on the validation:
- the warnings are not blocking the submission. It's just to verify that is expected. For example, you can see the warning: "Warning 602: The data frame does not contain projections for 'inc death' target(s)." It is expected here as the results are for CA only and `inc death` is national level only. So I will ignore this warning. 
- If a submission file contains only state level projection (one or multiple), the `location` column might be automatically identify as numeric even if it was submitted in a character format (with the trailing 0). In this case, a warning message will be automatically print on the validation but, please feel free to ignore it. 

Please feel free to let me know if you have any questions or if I can be of any help.
Thanks,

Lucie

[1] "Run validation on file: 2022-08-14-CADPH-FluCAT.csv"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 No errors or warnings found on Value and Type columns 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'inc death' target(s).
🟡 Warning 602: The data frame does not contain projections for 'cum death' target(s).
🟡 Warning 605: The projections should contains at least 42 weeks of projection. The data frame contains only: 39 week(s). The projection might not be included in the Ensembles.
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : A-2022-08-14, location : 6, target_name : cum hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : B-2022-08-14, location : 6, target_name : cum hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : C-2022-08-14, location : 6, target_name : cum hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : D-2022-08-14, location : 6, target_name : cum hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : A-2022-08-14, location : 6, target_name : inc hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : B-2022-08-14, location : 6, target_name : inc hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : C-2022-08-14, location : 6, target_name : inc hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : D-2022-08-14, location : 6, target_name : inc hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : A-2022-08-14, location : 6, target_name : peak time hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : B-2022-08-14, location : 6, target_name : peak time hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : C-2022-08-14, location : 6, target_name : peak time hosp
❌ Error 607: At least one target week is missing in the time series. Please verify: scenario_id : D-2022-08-14, location : 6, target_name : peak time hosp 

## Locations: 

 🟡 Warning 702: Some location value are missing a trailing 0. For example, 6 instead of 06 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by whit1951** [comment]
Hi Lucie, 
Thanks so much for the detailed validation! Per your comments on the warnings, just confirming that:
- per submission instructions, I did not include `inc deaths` or `cum deaths` since these are national and not state targets
- the location column is encoded as a character string, which I confirmed by opening in a text reader and also specifying `colClasses=c("location"="character")` for reading in the csv

Per the Warning 605/Error 607 messages, I have rectified a mistake in my filtering of the final submission, so there should now be 42 target weeks for all scenarios and all three targets.

Please let me know if I missed anything.

**Comment by LucieContamin** [comment]
Hi @whit1951 ,

Thank you very much for the quick update and the additional information, it looks all good now. 

I just have a small question for the abstract. I saw that you add multiple subsections and a `## Funding/Conflict of Interest` section. 
- For easier information extraction of the abstract, would it be possible to please avoid adding additional subsections in the abstract? 
- Just for information, the abstract is round related and a new one will be asked by round. The metadata file is not round related and is not expected to be updated each round. So, if you want to store the `## Funding/Conflict of Interest` information for multiple rounds, please feel free to use the metadata file, a `team_funding` field is available. The metadata fields: `name`, `version`, `methods`, `license` will be used on the website. 

Please feel free to let me know if you have any questions or if I can be of any help.
Many thanks,

Lucie

**Comment by whit1951** [comment]
Hi @LucieContamin,
I've:
- [x] moved the funding/COI to the metadata
- [x] removed any extra subheadings from the abstract

I mistakenly uploaded them in the `/MyTeam-MyModel/` sub-folder at first, so I apologize for the extra commits.
Thanks,
Lauren

**Comment by LucieContamin** [comment]
Hi @whit1951 ,

Thank you very much for all the updates and no problem for the commits. It all seems good now, I will merge the PR.

Best,
Lucie

**Pull request merged**
