### PR TITLE
USC-SIkJalpha round1 - 24-25

### PR DESCRIPTION
**Pull request by maa989**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @maa989,

Thanks for your submission, just to provide more information, it seems that your projection files is missing the column `run_grouping` and, as a reminder, the `output_type_id` column should be set to `NA` for `sample` output type. 

Please let me know if any issues or questions,

Best, Lucie

**Comment by LucieContamin** [comment]
Hi @maa989  ,

Thanks for the submission, I just wanted to verify that I understand the sample ID information correctly, so the submission contains 100 samples with:

   - Run_grouping: group by scenario, location, target, horizon, age group
   - Stochastic_run: all 1 (No stochasticity)

Is that correct?

Please let me know if any issues or questions,
Best, Lucie

**Comment by maa989** [comment]
Hi @LucieContamin, 
Yes that is correct. There is no stochasticity and the 100 samples are grouped by scenario, location, target, horizon, and age group.

Let me know if you have any other questions or concerns.

Best,
Majd

**Comment by LucieContamin** [comment]
Hi @maa989 ,

Thanks for the answer. I have another question if that's ok. It seems that the `stochastic_run` column contains `1` for all output type, will it be able to fix it so that it contains `1` for `sample` output type but `NA` for all the others output type, please?

Please let me know if any issues or questions,
Best, Lucie

**Comment by LucieContamin** [comment]
Hi @maa989 ,

Thanks for the update, just for information the `NA` in the output type id column is not read properly in R, you can set it up in the same way as how you set the `NA` in the `stochastic_run` and `run_grouping` columns for "quantile" value for example. 

Please let me know if any issues or questions,
Best, Lucie

**Comment by maa989** [comment]
Hi @LucieContamin,

I implemented a fix for the output type id column, but I couldn't set it up in the exact same way as I set the NA in the stochastic_run and run_grouping columns for "quantile" value. So please let me know if this fix still causes any issues or if you have any questions.

Best, 
Majd

**Comment by LucieContamin** [comment]
Thank you for the update, it seems to be all good now. 

Please let me know if any issues or questions,
Best, Lucie

**Pull request merged**
