### PR TITLE
PSI-M1 Round 2 submission

### PR DESCRIPTION
**Pull request by jturtle**
This is our first submission to Scenario Hub!  Please let us know if the submission files require any changes.

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @jturtle ,

Thank you for your submission. 
The automatic validation is currently not working, I am working to solve that and I apologize for the inconvenience.
In the meantime, I will run the validation manually and join the output in messages.

Please let me know if any issues or questions,

Best, Lucie

**Comment by LucieContamin** [comment]
[1] "Run validation on file: 2022-11-13-PSI-M1.csv"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 No errors or warnings found on Value and Type columns 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'inc death' target(s).
🟡 Warning 602: The data frame does not contain projections for 'cum death' target(s). 

## Locations: 

 No errors or warnings found on Location 

## Age Group: 

 No errors or warnings found on Age_group 
 
 
 The submission is accepted with Warnings, I just wanted to verify that this output was expected.
 Thanks, 
 Lucie

**Comment by LucieContamin** [comment]
[1] "Run validation on file: 2022-11-13-PSI-M1-sample.csv"

The validation seems to have some trouble with this file. It seems to contains multiple rows with NA value in multiple columns. "NA" are not expected in this file format, would it be possible to verify, please?

Thanks, Lucie

**Comment by jturtle** [comment]
Thank you for the update.  I will review my processing script to see where
the NAs are coming from, make corrections, and commit changes.
Cheers,
Jamie

**Comment by LucieContamin** [comment]
Hi Jamie, 

Thank you very much for the update, it seems to be all good now! I will merge the PR. 
Best, Lucie

**Pull request merged**
