### PR TITLE
Round 1 Flu

### PR DESCRIPTION
**Pull request by MPS7**
Hi, 

These are projections of our team. The abstract and metadata files are pending the validation of the rest of the team.

Best,
Anass

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @MPS7 ,

Thank you for your pull-request. 
The automatic validation is still in progress I apologize for the inconvenience. In the meantime, I will do the validation manually. Please find below this message the result of the validation.

Just for information, on the validation:
- the error "102" about a missing column is for the "age_group" column. As the age group is optional, should I understand that the projection are for the overall population (age_group: "0-130")? I manually added the column and set it to "0-130" for the rest of the validation. 

Please feel free to let me know if you have any questions or if I can be of any help.
Thanks,

Lucie

1] "Run validation on file: 2022-08-14-UT-ImmunoSEIRS.csv.gz"

 ## Columns: 

 ❌ Error 102: The data frame should contains 10 columns, not 9. Please verify if one or multiple columns have been added or are missing. 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 ❌ Error 502: The value type 'point' should have NA as 'quantile'. The data frame contains: '1' in the column 'quantile' for 'point' value. 

## Target Columns: 

 No errors or warnings found in target and target_end_date columns 

## Locations: 

 No errors or warnings found on Location 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by MPS7** [comment]
Hi Lucie,

Thank you for running the validation check. Indeed, the "age_group" column
should be "0-130". Thank you for adding it manually.

Best regards,
Anass

Le lun. 29 août 2022 à 09:29, Lucie Contamin ***@***.***> a
écrit :

**Comment by LucieContamin** [comment]
Hi Anass,

Thanks for the quick reply, just to clarify. I added the "age_group" column temporary for the validation only but I have not updated the submission file. 

Also, I can keep the PR open for the metadata and abstract files if preferred, 
Please feel free to let me know if you have any questions or if I can be of any help.
Thanks,

Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Thank you for the reply. I have uploaded the updated submission file, together with the abstract and the metadata.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,

Thank you for the update and for uploading the metadata and abstract files, please find below the results of the validation. 

For the metadata file, would it be possible to remove the first 2 lines, please:
```
#!!NOTE: THE METADATA BELOW ARE PURELY FOR THE PURPOSE OF DEMONSTRATING FILE FORMAT AND SHOULD NOT BE REGARDED IN ANY WAY AS INDICATIVE OF REASONABLE ASSUMPTIONS!!

```
These lines are just for the example file.

Please feel free to let me know if you have any questions or if I can be of any help.
Thanks,

Lucie

"Run validation on file: 2022-08-14-UT-ImmunoSEIRS.csv.gz"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 ❌ Error 502: The value type 'point' should have NA as 'quantile'. The data frame contains: '1' in the column 'quantile' for 'point' value. 

## Target Columns: 

 No errors or warnings found in target and target_end_date columns 

## Locations: 

 No errors or warnings found on Location 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by LucieContamin** [comment]
Hi Anass,

The abstract has been updated (https://github.com/midas-network/flu-scenario-modeling-hub/blob/main/data-processed/MyTeam-MyModel/2022-08-14-MyTeam-MyModel-abstract.md) to add a section on Model Calibration. 
Would it be possible to update your abstract accordingly, please?

Please feel free to let me know if you have any questions or if I can be of any help.
Many thanks,
Lucie

**Comment by MPS7** [comment]
Hi Lucie,

We have updated the abstract according to new format. Thank you.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,
Thanks for the abstract update. Could I ask if the issue in the projection file has been solved too?

Please feel free to let me know if you have any questions or if I can be of any help.
Many thanks,
Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Do you mean adding the age group case? Yes, it was resolved.

Best,
Anass

Le mar. 6 sept. 2022 à 07:36, Lucie Contamin ***@***.***> a
écrit :

**Comment by LucieContamin** [comment]
Hi Anass,

I mean the other error: 
`❌ Error 502: The value type 'point' should have NA as 'quantile'. The data frame contains: '1' in the column 'quantile' for 'point' value.`

Please feel free to let me know if you have any questions, 
Best,
Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Thank you. I have fixed the problem. I hope it will go well this time.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,

Thanks for the update, the validation has not been run entirely for a date format issue. Would it be possible to verify that all date are in the YYYY-MM-DD format, please?

Many thanks,
Lucie

**Comment by MPS7** [comment]
Thanks Lucie, I have fixed that now.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Thanks for the update. Please find below the validation output.

Please feel free to let me know if you have any questions or if I can be of any help.
Many thanks,
Lucie

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Sample: 

 No 'sample' information required, no validation runs for Sample information 

## Value and Type Columns: 

 No errors or warnings found on Value and Type columns 

## Target Columns: 

 No errors or warnings found in target and target_end_date columns 

## Locations: 

 🟡 Warning 702: Some location value are missing a trailing 0. For example, 1 instead of 01
🟡 Warning 702: Some location value are missing a trailing 0. For example, 2 instead of 02
🟡 Warning 702: Some location value are missing a trailing 0. For example, 4 instead of 04
🟡 Warning 702: Some location value are missing a trailing 0. For example, 5 instead of 05
🟡 Warning 702: Some location value are missing a trailing 0. For example, 6 instead of 06
🟡 Warning 702: Some location value are missing a trailing 0. For example, 8 instead of 08
🟡 Warning 702: Some location value are missing a trailing 0. For example, 9 instead of 09 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by LucieContamin** [comment]
Hi @MPS7 ,

Following the validation output, would it be possible to fix the location column please? It would help with the workflow. 

Please feel free to let me know if you have any questions,
Best,
Lucie

**Comment by MPS7** [comment]
Hi Lucie,

I have corrected the location column. 

Thank you.

Best,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,

Thanks for the update. Sorry to insist but the validation has not been run entirely for the date format issue. It seems that the data are in MM/DD/YYYY format again. Would it be possible to verify that all date are in the YYYY-MM-DD format, please?

Thanks
Lucie

**Comment by MPS7** [comment]
Thank you Lucie. I have corrected the date format again. I hope it will run well now.

Best,
Anass

**Comment by LucieContamin** [comment]
Thank you for the update, it seems to be all good now, I will merge the PR.
Best,
Lucie

1] "Run validation on file: 2022-08-14-UT-ImmunoSEIRS.zip"
[1] "End of validation check: all the validation checks were successfull"

**Comment by MPS7** [comment]
Thank you Lucie, do I need to fix the target column (add 0 to 1 for
example) or it's not a problem for the visualization on the dashboard?

Best regards,
Anass

Le mar. 6 sept. 2022 à 12:38, Lucie Contamin ***@***.***> a
écrit :

**Pull request merged**
