### PR TITLE
adding individual simulations file

### PR DESCRIPTION
**Pull request by aperofsky**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @aperofsky ,

Thank you for the submission, please find here the output of the validation. Let me know if any questions,

Best, Lucie

1] "Run validation on file: 2022-08-14-NIH-Flu_TS-sample.csv.zip"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No 'quantile' information required, no validation runs for Quantiles information 

## Sample: 

 ❌ Error 901: The column 'sample' should contains integer values between 1 and 100 (included), please verify. 

## Value and Type Columns: 

 No errors or warnings found on Value and Type columns 

## Target Columns: 

 🟡 Warning 602: The data frame does not contain projections for 'inc death' target(s). 

## Locations: 

 No errors or warnings found on Location 

## Age Group: 

 No errors or warnings found on Age_group

**Comment by aperofsky** [comment]
Hi @LucieContamin , apologies for the delay. I will resubmit with just 100 simulations per scenario. The warning for the target columns is expected since we are only providing hospitalizations.

**Comment by aperofsky** [comment]
@LucieContamin I've corrected the file to have 100 samples per scenario.

**Comment by LucieContamin** [comment]
Hi @aperofsky ,

Thanks for the update, it looks all good now. I will merge the PR.

Best, Lucie

**Pull request merged**
