### PR TITLE
Round 2 results

### PR DESCRIPTION
**Pull request by fardadhp**

### CODE REVIEW

**Comment by LucieContamin** [comment]
HI @fardadhp ,

Thank you for your submission. I just have a question about the round 1 projection file, it seems that you deleted it. Does that mean that you want to remove your submission from round 1?

Thanks,
Lucie

**Comment by fardadhp** [comment]
Hi Lucie,

I just was not sure if I was supposed to keep it or not when submitting round 2. Should I upload and request a pull?

**Comment by LucieContamin** [comment]
Hi again,

Normally we keep every round and just add another files when submitting for a new round. Would it be possible to either upload it back in this PR or in another PR (as you prefer, just please let me know so I can keep track, thanks!)?

Many thanks,
Lucie

**Comment by fardadhp** [comment]
I am going to submit now in this PR. Sorry for the misunderstanding. 

Thanks,
Fardad

**Comment by LucieContamin** [comment]
Thank you very much, and sorry about not warning you in advance!
I have another question, and I am sorry to insist, but would it be possible to keep the name of the round 1 file: "2022-08-14-CDDEP-FluCompModel.csv". You currently have an "_" in between the date and team/model name and it will cause issue in the processing. 

Many thanks again,
Lucie

**Comment by fardadhp** [comment]
Oops, sorry, forgot to correct that. Just submitted the correction. Thank you very much for all the work.

Fardad

**Comment by LucieContamin** [comment]
Thank you very much for the quick update and reply! I will wait the validation to end but it seems to be all good now!
Many thanks, Lucie

**Comment by fardadhp** [comment]
Great! Cheers..

**Pull request merged**
