### PR TITLE
Abstract for NIH TS Model Round 5

### PR DESCRIPTION
**Pull request by aperofsky**

### CODE REVIEW

**Review by LucieContamin — COMMENTED** [review]
Thank you for the abstract submission! It looks all good, I just have minor question, would it be possible to avoid the additional section (for example `## Cumulative hospitalizations` as it changes the file organization, maybe use instead bold or italic subtitle (for example `***Cumulative hospitalization***`

**Review by LucieContamin — COMMENTED** [review]
Sorry for the double message, but I also just noticed the name of the file needs to be updated, please.
It should be `data-processed/NIH-Flu_TS/2024-08-11-NIH-Flu_TS-abstract.md` with a `"-"` before `abstract.md`

Please let me know if any issues or questions,
Best, Lucie

**Comment by aperofsky** [comment]
@LucieContamin thanks for reviewing! I've made your suggested changes. Please let me know if there are any other issues.

**Review by LucieContamin — COMMENTED** [review]
Thank you very much for the update, would it be possible to remove the past version to avoid confusion, please?

**Comment by aperofsky** [comment]
@LucieContamin sorry I missed your message. I removed the old version with the incorrect file name.

**Review by LucieContamin — APPROVED** [review]
Thank you!

**Pull request merged**
