### PR TITLE
Phdl flu hub

### PR DESCRIPTION
**Pull request by johnskpaulxqe**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @johnskpaulxqe ,

Thanks for your submission, if I can add more information on the validation. 
The validation did not run because it required dates to be in "YYYY-MM-DD" format. It seems that the column `target_end_date` is in a "YYYY.WW" format in your submission files, would it be possible to verify please?
Also, for information, the location should be the FIPS code as in the [locations.csv](https://github.com/midas-network/flu-scenario-modeling-hub/blob/main/data-locations/locations.csv). The code should be in character format with the leading 0, for example, "04" for Arizona, etc. 

Please feel free to let me know if any issues or questions,

Thanks,
Lucie

**Comment by johnskpaulxqe** [comment]
Hi @LucieContamin 

We had worked only on two files with 20 runs 
1. Quantile and mean values of 2 strains
2. Values from individual runs (Run 1 through Run20)

Could you please by pass the validations for these before the deadline - I shall add the peak size and time soon

**Comment by johnskpaulxqe** [comment]
@LucieContamin This sample file went through successfully. If this is acceptable please complete the PR. We are working on the peak size for the MODEL file.

**Comment by LucieContamin** [comment]
Hi @johnskpaulxqe ,

Thanks for the update. However, the validation did not work properly as we don't have the output of the validation in the PR. It seems that the code had trouble with reading your file. 
Would it be possible to resubmit a new version of the file, please? (`.csv`, `.zip`, `.gz` and `parquet` file format are accepted.)

Many thanks, Lucie

**Comment by johnskpaulxqe** [comment]
@LucieContamin submitted the model without the peak value - 501 is the only error now

Error 501: The data frame is missing point value.

**Comment by LucieContamin** [comment]
The validation seems to have trouble reading your files. As I understand, it might be because of the compression, would it be possible to either submit a CSV file directly (if each file in < 100MB) or using another compression method?
Thanks,
Lucie

**Comment by LucieContamin** [comment]
Thanks for the update.
However, I cannot merge the PR until both files are either in CSV or other compression method and the previous `.gz` files are removed (the ones not passing the validation).
Please let me know if any questions or issues,

Best, Lucie

**Comment by johnskpaulxqe** [comment]
@LucieContamin I have removed the gz files

**Comment by LucieContamin** [comment]
Thanks for the update, it seems all good now. 
I just have a quick question for the metadata file, if the metadata file contains:
```
model_name: FREDModel
model_abbr: PHDL-FREDModel
```
The folder and the file names should follow the same upper/lower case rules.

So would it be possible to either rename the files or rename the metadata model fields so that both are matching? And also, would it be possible to remove the `<>` in the method field of the metadata, except if you want it to appears on the website?

Thanks,

Lucie

**Comment by johnskpaulxqe** [comment]
Hi @LucieContamin - could you please check it now and let me know if additional corrections are needed

**Comment by LucieContamin** [comment]
thanks for the update, 
I just have s mall modification on the metadata, would it be possible to put back the "<>" around the email information, please? I need to be able to differentiate it. 
Thanks, Lucie

**Comment by johnskpaulxqe** [comment]
@LucieContamin updated - could you please check and let me know if there is any other corrections needed

**Comment by LucieContamin** [comment]
Thanks for all the update. The format is all good now!

**Comment by johnskpaulxqe** [comment]
> Thanks for all the update. The format is all good now!

Thank you so much!

**Comment by johnskpaulxqe** [comment]
@LucieContamin - target name corrected to cum hospitalization in the model file

**Comment by johnskpaulxqe** [comment]
@LucieContamin  - missed your message on adding incident quantile in MODEL file - let me try that and will let you know in 20 minutes

**Comment by johnskpaulxqe** [comment]
@LucieContamin Let me know if there is anything to be updated

**Pull request merged**
