### PR TITLE
Round 4 submission

### PR DESCRIPTION
**Pull request by fardadhp**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @fardadhp ,

Thank you very much for your submissions.

The automatic validation seems to had some issue, I am working on fixing it. However, the validation requires the fork to be up to date to have all the required data, would it be possible to update your fork version? 
I apologize for the inconvenience. In the meantime, I will run the validation manually.

For the validation results:
- the submission data format has changed to `.parquet`, would it be possible to update your file format, please? (https://github.com/midas-network/flu-scenario-modeling-hub/tree/main/data-processed#model-results)
- On the manual validation runs, it returns an error:
`❌ Error 5041: All values should be greater or equal to 0 the data frame contains some error, please verify. `, would it be possible to look into it?

Also, it seems to me that your PR #66  is redundant with this one, am I correct? If so, can I close it?

Please feel free to let me know if you have any questions or if I can be of any help.
Thanks,

**Comment by fardadhp** [comment]
Hi @LucieContamin ,

Sorry about the data format. I though `.parquet` was just a suggestion. I will make a parquet file and update my fork version.
Yes, I submitted two times thinking maybe the first time was an internal error. 

Thanks,

**Comment by LucieContamin** [comment]
Thank you very much for all the updates. It looks all good now, I will merge your submission.

Please feel free to let me know if you have any questions,
Thanks,
Lucie

**Comment by fardadhp** [comment]
Thank you for all the hard work.

**Pull request merged**
